### PR TITLE
Added Greek translations (el_GR)

### PR DESCRIPTION
**Pull request by gmavrikas**
Greek translations for your awesome app!
Signed-off-by: Georgios Mavrikas <georgios@mavrikas.com>

### CODE REVIEW

**Comment by Kemmey** [comment]
Awesome! Thank you so much!

If you haven't already, please join the testflight at https://testflight.apple.com/join/FdzFOLZv to verify everything looks good! - I'll have the build ready in 30 mins-ish

Cheeers, 

Kim

**Comment by Kemmey** [comment]
@gmavrikas Would you like to be credited in the About screen as Georgios M or Georgios Mavrikas?

**Comment by gmavrikas** [comment]
You are welcome! I don’t have a Tesla yet, I am waiting for the 7-seater model Y to become available in Europe (I have 3 kids, a towable caravan and I also am in the waiting list for a dog, so we need _A LOT_ of space!)
If you would have the time, we could have a FaceTime video call and I can have a look at the watch display in Greek and do any cosmetic fixes.

Take care,
George

**Comment by gmavrikas** [comment]
Full name is fine, unless it does not fit. Thanks!

**Comment by Kemmey** [comment]
Hey, 

I did a recording of most of the app - this is actually a really good way to find localizations that I've missed - and there are a few! 

I also see that there are buttons that don't properly wrap - I'll add all that to my todo list and try to fix for 1.0.6 :-D

https://www.icloud.com/iclouddrive/0HJUnAFU--Now9EtjIv4z7lvw#WatchForTesla_1.0

**Comment by gmavrikas** [comment]
Looks very good for a first set of translations, I’ll send you a more streamlined version this afternoon!

**Pull request merged**
