### PR TITLE
Cosmetic fixes for el_GR translations

### PR DESCRIPTION
**Pull request by gmavrikas**
This should make things more compact for avoiding overflown strings
Signed-off-by: Georgios Mavrikas <georgios@mavrikas.com>

### CODE REVIEW

**Comment by Kemmey** [comment]
Brilliant! I'll have a new video up for you ASAP :-D 

Thank you so much!

**Comment by Kemmey** [comment]
Hey @gmavrikas 

Here's a video of the new translations: 

https://www.icloud.com/iclouddrive/0XIwT9I8KoFmq_Zqa7a3cEaRQ#WatchForTesla_1.0

I haven't updated wrapping of labels etc yet - but I can easily spot where I need to do some changes from your translations - I'll let you know when I've implemented that - then it should be possible to read all of the text...

**Comment by gmavrikas** [comment]
Looks great, let me know when you are done with wrapping, I could review again!

**Comment by Kemmey** [comment]
Hey @gmavrikas! I finally got around to fix the wrapping: 

https://www.icloud.com/iclouddrive/0MS1IjIeOp3Ek1_6DN7kCB3PA#WatchForTesla_1.0

I've added two keys for the missing charging states: 

"Starting" = "Starting";
"Charging" = "Charging";

Cheers, 

Kim

**Pull request merged**
