### PR TITLE
Create Localizable.strings

### PR DESCRIPTION
**Pull request by xMrVizzy**

### CODE REVIEW

**Comment by xMrVizzy** [comment]
I will receive my Tesla in November/December, so I will replenish and change the translation first based on the screenshots and then on my experience).

**Comment by Kemmey** [comment]
That is fantastic!

I'll grab the translations tomorrow and run a simulator build and send you a recording for verification, then we can do iterations until all looks good :-D

**Comment by xMrVizzy** [comment]
Nice! Thank you!

**Comment by Kemmey** [comment]
Hey @xMrVizzy - have a look at this screen recording for current status: 

https://www.icloud.com/iclouddrive/0Ze3tC9C9yoVEnOz2_LJYvXVw#Russian_1.0

**Comment by xMrVizzy** [comment]
Thank you so much, I got it! Now I can finish the translation!

**Pull request merged**
